GET http://localhost:8787/posts

###

GET http://localhost:8787/post/680235a5-6544-46e2-8490-f8130468181a

###

POST http://localhost:8787/post
Content-Type: application/json

{
  "title":"New Post Test",
  "content":"This is a new post Test",
  "authorId":"9c858901-8a57-4791-81fe-4c455b099bc9",
  "authorName":"John Doe"
}

###

PUT http://localhost:8787/post/680235a5-6544-46e2-8490-f8130468181a
Content-Type: application/json

{
  "title":"Updated Title Test",
   "content":"Updated Content Test"
}

###

DELETE http://localhost:8787/post/680235a5-6544-46e2-8490-f8130468181a


###